#!/usr/bin/env python
# coding: utf-8

# In[9]:


import pandas as pd
import git


# In[92]:


df = pd.read_csv('/home/priyak@talentica-all.com/Documents/Priya/Projects/DetectAutoGeneratedCode/cicero-backend/git-log-all-process.csv')
print(df)


repo_dir = '/home/priyak@talentica-all.com/Documents/Priya/Projects/DetectAutoGeneratedCode/cicero-backend/'
repo = git.Repo(repo_dir)
print (repo)


# In[93]:


gitlstree = f'git ls-tree HEAD -lr --full-name'
gitlstree_output = repo.git.execute(clean_git_command(gitlstree))


# In[94]:


def clean_git_command(command):
    return [keyword for keyword in command.split(' ') if keyword != '']


# In[26]:





# In[ ]:





# In[95]:


f = open("/home/priyak@talentica-all.com/Documents/Priya/Projects/DetectAutoGeneratedCode/cicero-backend/gitfiletree.csv", "w")
f.write('commit,paths_path,Size\n')
for line in linesplit:
    filenames=line.split('\t',1)
    commitId=line.split(' ')
    #print(filenames)
    filenames[0]= filenames[0].split(' ')[-1]
    f.write(commitId[2] + ',' +filenames[1] + ',' + filenames[0]+"\n")
f.close()


# In[ ]:





# In[96]:


df1= pd.read_csv('/home/priyak@talentica-all.com/Documents/Priya/Projects/DetectAutoGeneratedCode/cicero-backend/gitfiletree.csv')
print(df1)


# In[83]:


#df3=pd.concat([df, df1], axis=1, join="inner")
#print(df3.head(5))


# In[103]:


df3=(pd.merge(
    df,
    df1,
    how="inner",
    on='paths_path'
))
print(df3)

df3.to_csv('/home/priyak@talentica-all.com/Documents/Priya/Projects/DetectAutoGeneratedCode/cicero-backend/mergedData.csv')


# In[ ]:




